name: Build CI
on:
  push:
    branches: 
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Build and Publish Image
    steps:
      - name: Clone ldap-overleaf-sl
        run: |
          git clone https://github.com/smhaller/ldap-overleaf-sl.git .
      - name: Inject scheme-full into image
        run: echo "RUN tlmgr update --self && tlmgr install scheme-full" >> ldap-overleaf-sl/Dockerfile
      - name: Build ldap-overleaf-sl
        run: |
          bash scripts/extract_files.sh 4.2.0
          bash scripts/apply_diffs.sh
          make
      - name: Log into github registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag and push image
        run: |
          docker tag ldap-overleaf-sl ghcr.io/roblkyogre/ldap-overleaf-sl:latest
          docker push ghcr.io/roblkyogre/ldap-overleaf-sl:latest
