name: Build CI
on:
  push:
    branches: 
      - "main"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Build and Publish Image
    steps:
      - name: Clone cinny
        run: git clone -b dev https://github.com/cinnyapp/cinny.git .
      - name: Build cinny
        run: |
          docker build -t cinny:latest .
      - name: Log into github registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag and push image
        run: |
          docker tag cinny:latest ghcr.io/roblkyogre/cinny:latest
          docker push ghcr.io/roblkyogre/cinny:latest
